### PR TITLE
fix(row): remove calc from nth

### LINKED ISSUE #119: Build failed
Hello. I am using code from branch master, install dependencies, run ENB (./node_modules/.bin/enb make) and get the error:

```
12:57:19.792 - build failed
Error: CssSyntaxError: Number, odd or even is expected
Error result in /Users/z/Code/fiat-m.local/bower_components/bem-grid/dist/bem-grid.min.css.borschik-error
    at /Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/borschik/lib/tech.js:86:31
    at Array.<anonymous> (/Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/Users/z/Code/fiat-m.local/bower_components/bem-grid/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Error, because it's generate float number for :nth-child pseudo selector (for example: .row__col_sw_5:nth-child(2.4n), .row__col_sw_7:nth-child(1.71429n) )

How to fix? I'm running run ENB with default settings in ./enb/make.js

### PR DESCRIPTION
**Pull request by awinogradov**
Close #119

### CODE REVIEW

**Comment by bautrukevich** [comment]
Build passed, but grid crashed : (

`
<hr>
<h2 class="h2">BEM Grid</h2>

<style>
    .example-grid {
        background-color: #ddd;
        text-align: center;
        padding: 8px;
    }
    .example-grid-large {
        background-color: #ddd;
        text-align: center;
        padding: 16px;
    }
</style>

<p>Alight left</p>

<div class="row row_mal">
    <div class="row__col row__col_mw_2 example-grid">Align left</div>
    <div class="row__col row__col_mw_2 example-grid">Align left</div>
</div>


<p>Alight center</p>

<div class="row row_mac">
    <div class="row__col row__col_mw_2 example-grid">Align center</div>
    <div class="row__col row__col_mw_2 example-grid">Align center</div>
</div>


<p>Alight right</p>

<div class="row row_mar">
    <div class="row__col row__col_mw_2 example-grid">Align right</div>
    <div class="row__col row__col_mw_2 example-grid">Align right</div>
</div>


<p>Vertical align top</p>

<div class="row">
    <div class="row__col row__col_mw_3 example-grid-large">3</div>
    <div class="row__col row__col_mw_3">
        <div class="row row_mvat row_end" style="height: 100px;">
            <div class="row__col row__col_mw_12 example-grid">3</div>
        </div>
    </div>

</div>


<p>Vertical align middle</p>

<div class="row">
    <div class="row__col row__col_mw_3 example-grid-large">3</div>
    <div class="row__col row__col_mw_3">
        <div class="row row_mvam row_end" style="height: 100px;">
            <div class="row__col row__col_mw_12 example-grid">3</div>
        </div>
    </div>

</div>


<p>Vertical align bottom</p>

<div class="row">
    <div class="row__col row__col_mw_3 example-grid-large">3</div>
    <div class="row__col row__col_mw_3">
        <div class="row row_mvab row_end" style="height: 100px;">
            <div class="row__col row__col_mw_12 example-grid">3</div>
        </div>
    </div>

</div>


<p>Sizes</p>

<div class="row">
    <div class="row__col row__col_mw_1 example-grid">1</div>
    <div class="row__col row__col_mw_11 example-grid">11</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_2 example-grid">2</div>
    <div class="row__col row__col_mw_10 example-grid">10</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_3 example-grid">3</div>
    <div class="row__col row__col_mw_9 example-grid">9</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_4 example-grid">4</div>
    <div class="row__col row__col_mw_8 example-grid">8</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_5 example-grid">5</div>
    <div class="row__col row__col_mw_7 example-grid">7</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_6 example-grid">6</div>
    <div class="row__col row__col_mw_6 example-grid">6</div>
</div>


<p>Offset</p>

<div class="row">
    <div class="row__col row__col_mo_11 row__col_mw_1 example-grid">Offset 1</div>
</div>

<div class="row">
    <div class="row__col row__col_mw_3 row__col_mo_2"></div>
    <div class="row__col row__col_mw_3 example-grid">Offset 2</div>
</div>

<p>Order first</p>

<div class="row">
    <div class="row__col row__col_mw_4 example-grid">Order 1</div>
    <div class="row__col row__col_mw_4 example-grid">Order 2</div>
    <div class="row__col row__col_mw_4 row__col_mof example-grid">Order 3</div>
</div>


<p>Order last</p>

<div class="row">
    <div class="row__col row__col_mw_4 row__col_mol example-grid">Order 1</div>
    <div class="row__col row__col_mw_4 example-grid">Order 2</div>
    <div class="row__col row__col_mw_4 example-grid">Order 3</div>
</div>


<p>Order reverse</p>

<div class="row row_order_reverse">
    <div class="row__col row__col_mw_4 example-grid">Order 1</div>
    <div class="row__col row__col_mw_4 example-grid">Order 2</div>
    <div class="row__col row__col_mw_4 example-grid">Order 3</div>
</div>
`

bemgrid

But previous works more fine. Only have a bug with row-reverse order (last item don't have right margin)

**Comment by awinogradov** [comment]
Ok, I'll write some tests for that in a few days. You problem can be solved by repair `calc` function.

**Comment by bautrukevich** [comment]
Ok, thank you!

**Comment by awinogradov** [comment]
@bautrukevich now it should works fine ;) test it!

**Comment by awinogradov** [comment]
all fixed

**Comment by awinogradov** [comment]
@bautrukevich `bem-grid@2.5.0`

**Comment by bautrukevich** [comment]
Thank you! It's looks great!

**Pull request merged**
